# ВНИМАНИЕ! ЭТО БЕТА НЕ ДЛЯ REMNAWAVE, А ДЛЯ РУЧНОЙ ВСТАВКИ
proxy-providers:
  prov:
    type: http
    url: <ВВЕДИТЕ URL ПОДПИСКИ> # в формате mihomo. для Remnawave необходимо в настройках включить mihomo.
    path: ./provider/proxies.yaml
    interval: 86400
# Если нет ссылки - удалите блок выше, расскоментируйте блок ниже и заполните
# можете воспользоваться конвертером https://dikozimpact.github.io/clash-convertor/
#proxies:
#- name: <PROXYNAME> (EXAMPLE)
#  type: vless
#  server: <server address>
#  port: 443
#  ip-version: ipv4
#  uuid: <uuid>
#  network: tcp
#  tls: true
#  udp: true
#  flow: xtls-rprx-vision
#  servername: <servername>
#  reality-opts:
#    public-key: <public key>
#    short-id: <shot id>
#    support-x25519mlkem768: true
#  client-fingerprint: chrome
#- name: <Another name>
mixed-port: 7890
mode: rule
log-level: silent
allow-lan: false
ipv6: false
unified-delay: true
tcp-concurrent: true
disable-keep-alive: true
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  strict-route: true
  route-exclude-address:
  - 224.0.0.0/3
  - 10.0.0.0/8
  - 127.0.0.0/8
  - 100.64.0.0/10
  - 172.16.0.0/12
  - 169.254.0.0/16
  - 192.168.0.0/16
  - 192.0.0.0/24
  - 192.0.2.0/24
  - 192.88.99.0/24
  - 198.51.100.0/24
  - 203.0.113.0/24
  - fc00::/7
  - ff00::/8
  - fe80::/10
  - ::/127
dns:
  enable: true
  use-hosts: true
  use-system-hosts: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - rule-set:private-domains
  default-nameserver:
  - 77.88.8.8
  proxy-server-nameserver:
  - 77.88.8.8
  direct-nameserver:
  - 77.88.8.8
  nameserver:
  - 76.76.2.41#PROXY
sniffer:
  enable: true
  override-destination: false
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8880
    TLS:
      ports:
      - 443
      - 8443
  skip-dst-address:
  - 224.0.0.0/3
  - 10.0.0.0/8
  - 127.0.0.0/8
  - 100.64.0.0/10
  - 172.16.0.0/12
  - 169.254.0.0/16
  - 192.168.0.0/16
  - 192.0.0.0/24
  - 192.0.2.0/24
  - 192.88.99.0/24
  - 198.51.100.0/24
  - 203.0.113.0/24
  - fc00::/7
  - ff00::/8
  - fe80::/10
  - ::/127
find-process-mode: always
profile:
  store-selected: true
  store-fake-ip: true
proxy-groups:
- name: 🛡️ VPN
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Hijacking.png
  type: select
  proxies:
  - ⚡️ Авто
  include-all: true
  url: https://www.gstatic.com/generate_204
- name: 💬 Discord.exe
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Discord.png
  type: select
  include-all: true
  proxies:
  - 🛡️ VPN
  - 🔓 Без VPN
- name: 🎮 Игры
  icon: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Color/Game.png
  type: select
  proxies:
  - 🛡️ VPN
  - 🔓 Без VPN
- name: ⚡️ Авто
  type: url-test
  tolerance: 150
  url: https://www.gstatic.com/generate_204
  interval: 300
  include-all: true
  hidden: true
- name: PROXY
  type: select
  hidden: true
  proxies:
  - 🛡️ VPN
- name: 🔓 Без VPN
  type: select
  hidden: true
  proxies:
  - DIRECT
- name: ⛔ Блок
  type: select
  hidden: true
  proxies:
  - REJECT
- name: ⏭️ Пропуск
  type: select
  hidden: true
  proxies:
  - PASS
rule-providers:
  private-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geoip/release/mihomo/private.mrs
    path: ./ruleset/geoip-private.mrs
    interval: 2592000
  private-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/private.mrs
    path: ./ruleset/geosite-private.mrs
    interval: 2592000
  category-ads:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/category-ads.mrs
    path: ./ruleset/category-ads.mrs
    interval: 86400
  win-spy:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/win-spy.mrs
    path: ./ruleset/win-spy.mrs
    interval: 86400
  torrent-clients:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/legiz-ru/mihomo-rule-sets/main/other/torrent-clients.yaml
    path: ./ruleset/torrent-clients.yaml
    interval: 86400
  torrent-domains:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/torrent-domains.mrs
    path: ./ruleset/torrent-domains.mrs
    interval: 86400
  twitch-ads:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/twitch-ads.mrs
    path: ./ruleset/twitch-ads.mrs
    interval: 86400
  games:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/roscomvpn/custom-category/release/mihomo/games.yaml
    path: ./ruleset/games.yaml
    interval: 86400
  ru-apps:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/roscomvpn/custom-category/release/mihomo/ru-apps.yaml
    path: ./ruleset/ru-apps.yaml
    interval: 86400
  category-ru:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/category-ru.mrs
    path: ./ruleset/category-ru.mrs
    interval: 86400
  microsoft:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/microsoft.mrs
    path: ./ruleset/microsoft.mrs
    interval: 86400
  apple:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/apple.mrs
    path: ./ruleset/apple.mrs
    interval: 86400
  google-play:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/google-play.mrs
    path: ./ruleset/google-play.mrs
    interval: 86400
  epicgames:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/epicgames.mrs
    path: ./ruleset/epicgames.mrs
    interval: 86400
  riot:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/riot.mrs
    path: ./ruleset/riot.mrs
    interval: 86400
  escapefromtarkov:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/escapefromtarkov.mrs
    path: ./ruleset/escapefromtarkov.mrs
    interval: 86400
  steam:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/steam.mrs
    path: ./ruleset/steam.mrs
    interval: 86400
  twitch:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/twitch.mrs
    path: ./ruleset/twitch.mrs
    interval: 86400
  pinterest:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/pinterest.mrs
    path: ./ruleset/pinterest.mrs
    interval: 86400
  faceit:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/release/mihomo/faceit.mrs
    path: ./ruleset/faceit.mrs
    interval: 86400
  direct-ips:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/hydraponique/roscomvpn-geoip/release/mihomo/direct.mrs
    path: ./ruleset/direct-ips.mrs
    interval: 86400

rules:
- RULE-SET,private-ips,DIRECT,no-resolve
- RULE-SET,private-domains,DIRECT
- AND,((NETWORK,UDP),(OR,((DST-PORT,443),(DST-PORT,853)))),REJECT
- OR,((RULE-SET,category-ads),(RULE-SET,win-spy)),REJECT
- OR,((RULE-SET,torrent-clients),(RULE-SET,torrent-domains)),DIRECT
- OR,((PROCESS-NAME,Discord.exe),(PROCESS-NAME,discord),(PROCESS-NAME,vesktop)),💬 Discord.exe
- RULE-SET,twitch-ads,PROXY
- RULE-SET,games,🎮 Игры
- RULE-SET,ru-apps,DIRECT
- RULE-SET,category-ru,DIRECT
- RULE-SET,microsoft,DIRECT
- RULE-SET,apple,DIRECT
- RULE-SET,google-play,DIRECT
- RULE-SET,epicgames,DIRECT
- RULE-SET,riot,DIRECT
- RULE-SET,escapefromtarkov,DIRECT
- RULE-SET,steam,DIRECT
- RULE-SET,twitch,DIRECT
- RULE-SET,pinterest,DIRECT
- RULE-SET,faceit,DIRECT
- RULE-SET,direct-ips,DIRECT
- MATCH,PROXY
